version: 2.1
orbs:
  architect: giantswarm/architect@4.34.1

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-api-monitoring"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: gcp-app-collection
          context: "architect"
          app_name: "cluster-api-monitoring"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          # Trigger job on git tag.
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: cloud-director-app-collection
          context: "architect"
          app_name: "cluster-api-monitoring"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          # Trigger job on git tag.
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: capa-app-collection
          context: "architect"
          app_name: "cluster-api-monitoring"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          # Trigger job on git tag.
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: vsphere-app-collection
          context: "architect"
          app_name: "cluster-api-monitoring"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          # Trigger job on git tag.
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: capz-app-collection
          context: "architect"
          app_name: "cluster-api-monitoring"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          # Trigger job on git tag.
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
