{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "name" . }}
  namespace: {{.Release.Namespace}}
  labels: {{- include "labels.common" . | nindent 4}}
spec:
  endpointSelector:
    matchLabels: {{- include "labels.selector" . | nindent 6}}
  egress:
    - toEntities:
        - kube-apiserver
  ingress:
    - fromEntities:
      - cluster
      toPorts:
      - ports:
          - port: "8080"
{{- end }}
