apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "name" .}}
  namespace: {{.Release.Namespace}}
  labels: {{- include "labels.common" . | nindent 4}}
data:
  config.yaml: |
    kind: CustomResourceStateMetrics
    spec:
      resources:
{{- range $componentKey, $componentVal := .Values.monitoredResources }}
  {{- range $key, $val := $componentVal }}
    {{- if $.Files.Get (printf "configuration/%s_%s.yaml" $componentKey $key) }}
      - groupVersionKind:
          group: {{ $val.group }}
          kind: {{ $val.kind }}
          version: {{ $val.version }}
        namespace: {{ $componentKey }}
        subsystem: {{ $key }}
{{ $.Files.Get (printf "configuration/%s_%s.yaml" $componentKey $key) | indent 8}}
    {{ end }}
  {{- end }}
{{- end }}
