apiVersion: v1
kind: Service
metadata:
  name: {{include "name" .}}
  namespace: {{.Release.Namespace}}
  labels: {{- include "labels.common" . | nindent 4}}
spec:
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector: {{- include "labels.selector" . | nindent 4}}
