name: cluster-api-monitoring
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/kube-state-metrics
  tag: v0.0.1
  pullPolicy: v2.5.0-crd-support-marioc-2
