name: cluster-api-monitoring
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/kube-state-metrics
  tag: v2.5.0-additional-metric-types-e6eda699
  # v2.5.0-additional-metric-types-e6eda699  is based on commit e6eda699 of PR https://github.com/kubernetes/kube-state-metrics/pull/1777
  pullPolicy: IfNotPresent

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: "RuntimeDefault"

resources:
  limits:
    memory: 30Mi
  requests:
    memory: 30Mi

# List of CRs to monitor
monitoredResources:
  # first level of the map can be seen as a "group" to combine/organize multiple CRs.
  # This will lead to the first part of the generated metric name e.g. `flux_`
  #
  # flux:
  #   second level of the map should be used to name (in singular) the name of the CR.
  #   This will lead to second part of the generated metric name e.g. `flux_gitrepository_`
  #
  #   gitrepository:
  #     group: samplecontroller.k8s.io # group is the API group the CR belongs to
  #     kind: Foo                      # kind is the kind of the CR
  #     version: v1alpha1              # version is the version of the CR
  #     plural: foos                   # plural has to be the lower case plural string of kind - required for ClusterRole templating and must be done as KSM register resources as plural (doesn't matter if core Kubernetes or CRs)
  capi:
    machinehealthcheck:
      group: cluster.x-k8s.io
      kind: MachineHealthCheck
      version: v1beta1
      plural: machinehealthchecks
    machinedeployment:
      group: cluster.x-k8s.io
      kind: MachineDeployment
      version: v1beta1
      plural: machinedeployments
