labelsFromPath:
  name: [metadata, name]
  namespace: [metadata, namespace]
  cluster_name: [metadata, name]
metrics:
  - name: info
    help: Information about a vcdcluster.
    each:
      type: Info
      info:
        labelsFromPath:
          site: [spec, site]
          rde_id: [spec, rdeId]
          control_plane_endpoint_ip: [spec, controlPlaneEndpoint, host]
          control_plane_endpoint_port: [spec, controlPlaneEndpoint, port]
          org: [spec, org]
          ovdc: [spec, ovdc]
          ovdc_network: [spec, ovdcNetwork]
          vip_subnet: [spec, loadBalancerConfigSpec, vipSubnet]
  - name: annotation_paused
    help: Whether the vcdcluster is paused and any of its resources will not be processed by the controllers.
    each:
      info:
        path:
          - metadata
          - annotations
          - cluster.x-k8s.io/paused
        labelsFromPath:
          paused_value: []
      type: Info
  - name: status_conditions
    help: The conditions of an vcdcluster.
    each:
      type: StateSet
      stateSet:
        path:
          - status
          - conditions
        list:
          - "True"
          - "False"
          - "Unknown"
        valueFrom:
          - status
        labelName: status
        labelsFromPath:
          type: [type]
  - name: created
    each:
      gauge:
        path:
          - metadata
          - creationTimestamp
      type: Gauge
    help: Unix creation timestamp.
  - name: status_ready
    help: Information if the provider resource is ready.
    each:
      type: Gauge
      gauge:
        path:
          - status
          - ready
