labelsFromPath:
  cluster_name:
    - spec
    - clusterName
  name:
    - metadata
    - name
  namespace:
    - metadata
    - namespace
  uid:
    - metadata
    - uid
metrics:
  - name: info
    help: Information about a machinehealthcheck.
    each:
      info:
        # TODO: added metadata.name even it's already defined above as the metric doesn't work with empty labelsFromPath.
        labelsFromPath:
          name:
            - metadata
            - name
      type: Info
  - name: status_current_healthy
    help: Current number of healthy machines.
    each:
      gauge:
        path:
          - status
          - currentHealthy
      type: Gauge
  - name: status_expected_machines
    help: Total number of pods counted by this machinehealthcheck.
    each:
      gauge:
        path:
          - status
          - expectedMachines
      type: Gauge
  - name: status_remediations_allowed
    help: Number of machine remediations that are currently allowed.
    each:
      gauge:
        path:
          - status
          - remediationsAllowed
      type: Gauge
  - name: created
    help: Unix creation timestamp.
    each:
      gauge:
        path:
          - metadata
          - creationTimestamp
      type: Gauge
  - name: annotation_paused
    help: Whether the machinehealthcheck is paused and any of its resources will not be processed by the controllers.
    each:
      info:
        path:
          - metadata
          - annotations
          - cluster.x-k8s.io/paused
        labelsFromPath:
          paused_value: []
      type: Info
  - name: status_condition
    help: The condition of a machinehealthcheck.
    each:
      stateSet:
        labelName: status
        labelsFromPath:
          type:
            - type
        list:
          - "True"
          - "False"
          - Unknown
        path:
          - status
          - conditions
        valueFrom:
          - status
      type: StateSet
  - name: status_condition_last_transition_time
    help: The condition last transition time of a machinehealthcheck.
    each:
      gauge:
        labelsFromPath:
          type:
            - type
          status:
            - status
        path:
          - status
          - conditions
        valueFrom:
          - lastTransitionTime
      type: Gauge
  - name: owner
    help: Owner references.
    each:
      info:
        labelsFromPath:
          owner_is_controller:
            - controller
          owner_kind:
            - kind
          owner_name:
            - name
          owner_uid:
            - uid
        path:
          - metadata
          - ownerReferences
      type: Info
