labelsFromPath:
  cluster_name:
    - metadata
    - labels
    - cluster.x-k8s.io/cluster-name
  name:
    - metadata
    - name
  namespace:
    - metadata
    - namespace
  uid:
    - metadata
    - uid
metrics:
  - name: annotation_paused
    help: Whether the vcdmachine is paused and any of its resources will not be processed by the controllers.
    each:
      info:
        path:
          - metadata
          - annotations
          - cluster.x-k8s.io/paused
        labelsFromPath:
          paused_value: []
      type: Info
  - name: status_conditions
    help: The conditions of a vcdmachine.
    each:
      type: StateSet
      stateSet:
        path:
          - status
          - conditions
        list:
          - "True"
          - "False"
          - "Unknown"
        valueFrom:
          - status
        labelName: status
        labelsFromPath:
          type: [type]
  - name: info
    help: Information about a vcdmachine.
    each:
      type: Info
      info:
        labelsFromPath:
          bootstrapped:
            - spec
            - bootstrapped
          catalog:
            - spec
            - catalog
          resource_pool:
            - spec
            - resourcePool
          sizing_policy:
            - spec
            - sizingPolicy
          os_disk_size:
            - spec
            - diskSize
          template:
            - spec
            - template
  - name: addresses
    help: Information about vcdmachine network addresses.
    each:
      type: Info
      info:
        path:
          - status
          - addresses
        labelsFromPath:
          type:
            - type
          address:
            - address
  - name: status_ready
    help: Information if the provider resource is ready.
    each:
      type: Gauge
      gauge:
        path:
          - status
          - ready
  - name: created
    help: Unix creation timestamp.
    each:
      gauge:
        path:
          - metadata
          - creationTimestamp
      type: Gauge
  - name: owner
    help: Owner references.
    each:
      info:
        labelsFromPath:
          owner_is_controller:
            - controller
          owner_kind:
            - kind
          owner_name:
            - name
          owner_uid:
            - uid
        path:
          - metadata
          - ownerReferences
      type: Info
