labelsFromPath:
  version: [spec, template, spec, version]
  name: [metadata, name]
  namespace: [metadata, namespace]
  cluster_name: [spec, clusterName]
metrics:
  - name: status_conditions
    help: The current status conditions of a machinedeployment.
    each:
      stateSet:
        labelName: status
        labelsFromPath:
          type:
            - type
        list:
          - "True"
          - "False"
          - Unknown
        path:
          - status
          - conditions
        valueFrom:
          - status
      type: StateSet
  - name: spec_replicas
    each:
      type: Gauge
      gauge:
        path:
          - spec
          - replicas
  - name: status_replicas
    each:
      type: Gauge
      gauge:
        path:
          - status
          - replicas
        nilIsZero: true
  - name: status_replicas_ready
    each:
      type: Gauge
      gauge:
        path:
          - status
          - readyReplicas
        nilIsZero: true
  - name: status_replicas_available
    each:
      type: Gauge
      gauge:
        path:
          - status
          - availableReplicas
        nilIsZero: true
  - name: status_unavailable_replicas
    each:
      type: Gauge
      gauge:
        path:
          - status
          - unavailableReplicas
        nilIsZero: true
  - name: info
    each:
      type: Info
      info:
        labelsFromPath:
          infrastructure_reference_name:
            [spec, template, spec, infrastructureRef, name]
          infrastructure_reference_type:
            [spec, template, spec, infrastructureRef, kind]
          bootstrap_configuration_reference_name:
            [spec, template, spec, bootstrap, configRef, name]
          bootstrap_configuration_reference_type:
            [spec, template, spec, bootstrap, configRef, type]
          failure_domain: [spec, template, spec, failureDomain]
  - name: status_phase
    each:
      type: StateSet
      stateSet:
        path:
          - status
          - phase
        list:
          - Running
          - ScalingUp
          - ScalingDown
          - Failed
          - Unknown
        labelName: phase
  - each:
      gauge:
        path:
          - metadata
          - creationTimestamp
      type: Gauge
    name: created
    help: Unix creation timestamp.
  - each:
      gauge:
        nilIsZero: true
        path:
          - spec
          - paused
      type: Gauge
    name: spec_paused
