labelsFromPath:
  cluster_name:
    - metadata
    - labels
    - cluster.x-k8s.io/cluster-name
  name:
    - metadata
    - name
  namespace:
    - metadata
    - namespace
  uid:
    - metadata
    - uid
metrics:
  - name: info
    help: Information about a kubeadmconfig.
    each:
      info:
        # TODO: added metadata.name even it's already defined above as the metric doesn't work with empty labelsFromPath.
        labelsFromPath:
          name:
            - metadata
            - name
      type: Info
  - name: created
    help: Unix creation timestamp.
    each:
      gauge:
        path:
          - metadata
          - creationTimestamp
      type: Gauge
  - name: annotation_paused
    help: Whether the kubeadmconfig is paused and any of its resources will not be processed by the controllers.
    each:
      info:
        path:
          - metadata
          - annotations
          - cluster.x-k8s.io/paused
        labelsFromPath:
          paused_value: []
      type: Info
  - name: status_condition
    help: The condition of a kubeadmconfig.
    each:
      stateSet:
        labelName: status
        labelsFromPath:
          type:
            - type
        list:
          - 'True'
          - 'False'
          - Unknown
        path:
          - status
          - conditions
        valueFrom:
          - status
      type: StateSet
  - name: status_condition_last_transition_time
    help: The condition last transition time of a kubeadmconfig.
    each:
      gauge:
        labelsFromPath:
          type:
            - type
          status:
            - status
        path:
          - status
          - conditions
        valueFrom:
          - lastTransitionTime
      type: Gauge
  - name: owner
    help: Owner references.
    each:
      info:
        labelsFromPath:
          owner_is_controller:
            - controller
          owner_kind:
            - kind
          owner_name:
            - name
          owner_uid:
            - uid
        path:
          - metadata
          - ownerReferences
      type: Info
