labelsFromPath:
  name: [metadata, name]
  cluster_name: [metadata, name]
  namespace: [metadata, namespace]
metrics:
  - name: status_conditions
    help: The current status conditions of a cluster.
    each:
      type: StateSet
      stateSet:
        path:
          - status
          - conditions
        list:
          - "True"
          - "False"
          - "Unknown"
        valueFrom:
          - status
        labelName: status
        labelsFromPath:
          type: [type]
  - name: info
    each:
      type: Info
      info:
        labelsFromPath:
          control_plane_endpoint_host: [spec, controlPlaneEndpoint, host]
          control_plane_endpoint_port: [spec, controlPlaneEndpoint, port]
          control_plane_reference_kind: [spec, controlPlaneRef, kind]
          control_plane_reference_name: [spec, controlPlaneRef, name]
          infrastructure_reference_kind: [spec, infrastructureRef, kind]
          infrastructure_reference_name: [spec, infrastructureRef, name]
  - name: status_phase
    each:
      type: StateSet
      stateSet:
        path:
          - status
          - phase
        list:
          - Pending
          - Provisioning
          - Provisioned
          - Deleting
          - Failed
          - Unknown
        labelName: phase
  - name: created
    help: Unix creation timestamp.
    each:
      type: Gauge
      gauge:
        path:
          - metadata
          - creationTimestamp
  - name: spec_paused
    each:
      type: Gauge
      gauge:
        nilIsZero: true
        path:
          - spec
          - paused
