labelsFromPath:
  name: [metadata, name]
  namespace: [metadata, namespace]
metrics:
  - name: status_conditions
    help: The current status conditions of a cluster.
    each:
      type: StateSet
      stateSet:
        path:
          - status
          - conditions
        list:
          - "True"
          - "False"
          - "Unknown"
        valueFrom:
          - status
        labelName: status
        labelsFromPath:
          type: [type]
  - name: info
    each:
      type: Info
      info:
        labelsFromPath:
          branch: [spec, ref, branch]
          url: [spec, url]
          control_plane_reference_kind: [spec, controlPlaneRef, kind]
          control_plane_reference_name: [spec, controlPlaneRef, name]
          infrastructure_reference_kind: [spec, infrastructureRef, kind]
          infrastructure_reference_name: [spec, infrastructureRef, name]
  - name: status_artifact_last_update_time
    help: Unix update timestamp.
    each:
      type: Gauge
      gauge:
        path:
          - status
          - artifact
          - lastUpdateTime
