metrics:
  - name: "resource_info"
    help: "The current state of a Flux Bucket resource."
    each:
      type: Info
      info:
        labelsFromPath:
          name: [ metadata, name ]
    labelsFromPath:
      exported_namespace: [ metadata, namespace ]
      ready: [ status, conditions, "[type=Ready]", status ]
      suspended: [ spec, suspend ]
      revision: [ status, artifact, revision ]
      endpoint: [ spec, endpoint ]
      bucket_name: [ spec, bucketName ]
