metrics:
  - name: "resource_info"
    help: "The current state of a Flux Alert resource."
    each:
      type: Info
      info:
        labelsFromPath:
          name: [ metadata, name ]
    labelsFromPath:
      exported_namespace: [ metadata, namespace ]
      suspended: [ spec, suspend ]
